### ISSUE TITLE
Haskell has lambdas too!

### ISSUE THREAD

**Issue by treywood** [wolfadex/elm-haskell-cheat-sheet#2]
Regarding this bit:

Elm | Haskell
----|-----------
`\x -> x / 2` | `(/ 2)`

The Elm syntax for a lambda, `\x -> x / 2` is valid Haskell as well! What you've got in the Haskell column is called an [operator section](https://wiki.haskell.org/Section_of_an_infix_operator), which is sort of the curried or partially applied version of an infix operator.

**Comment by wolfadex** [comment]
Yeah, this one was to show more the side of Haskell and being able to use the operator section. You could also do something like `flip (/) 2`, but that's still not quite the same, especially since Elm doesn't have a built in `flip`.

I partially put this here too because I periodically see people in the Elm Slack try `((/) 2)` and then get confused as to why they didn't get half of their input.

**Comment by treywood** [comment]
Ah gotcha! I misread the Note for that row as though you wished Haskell supported `\x -> x / 2`.

Related - I sorely miss Elm's record dot syntax for field access when i'm working in Haskell. `map (.field) records` is so nice and only kinda works in Haskell: `map field records` except it breaks down quickly if you have multiple record types with the same field name in scope :(

Praying for [this proposal](https://ghc-proposals.readthedocs.io/en/latest/proposals/0282-record-dot-syntax.html) to see light of day
